name: Continuous Integration
on: [push, pull_request]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
        env:
          AUTH_SECRET: 'pr_check'